### ISSUE TITLE
File not found issue.

### ISSUE THREAD

**Issue by nerdprogrammergm** [ravi72munde/Chrome-Dino-Reinforcement-Learning#2]
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Now we build the model
We finish building the model
Traceback (most recent call last):
  File "Chrome-dino.py", line 444, in <module>
    playGame(observe=False);
  File "Chrome-dino.py", line 373, in playGame
    trainNetwork(model,game_state,observe=observe)
  File "Chrome-dino.py", line 223, in trainNetwork
    D = load_obj("D") #deque()
  File "Chrome-dino.py", line 155, in load_obj
    with open('objects/' + name + '.pkl', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'objects/D.pkl'

The above is my terminal log, I am trying to run it in mac, looking forward if someone can help me resolve this issue.

**Comment by ravi72munde** [comment]
Hey, there are few files that we need create before we start. Try calling 

`init_cache()`

once. Don't run it again as it will reset data structure. Thanks for reporting this. I will add this to instructions.

**Comment by nerdprogrammergm** [comment]
there is no function named init_cache() in the Chrome-driver.py
Can you jot down the complete steps cuz I am serious about learning this stuff.

**Comment by ravi72munde** [comment]
Actually you should refer to the jupyter notebook mention in Readme not the .py file. thanks for bringing that up.
