### ISSUE TITLE
Notebook fail to load on windows10 using Reinforcement Learning Dino Run.ipynb

### ISSUE THREAD

**Issue by easytrader** [ravi72munde/Chrome-Dino-Reinforcement-Learning#3]
The error was:

TypeError: Cannot read property 'length' of undefined
See the error console for details.

<img width="510" alt="fail" src="https://user-images.githubusercontent.com/15394723/40353988-647e8786-5de5-11e8-882f-8594b5e3add0.png">

**Comment by ravi72munde** [comment]
There was an illegal cell format in the notebook. It is fixed now. Thanks
