### ISSUE TITLE
Doubt on javascript 

### ISSUE THREAD

**Issue by Shekharrajak** [ravi72munde/Chrome-Dino-Reinforcement-Learning#5]
Thanks for this article. I didn’t understand how did you know `Runner` is for checking the state like current score, gamer running or not, crashed or not, resume, start, …

Is that present in every canvas game? Mean did it work only for chrome://dino ? How can I find out `Runner` kind of variable to check the game state in other websites?

**Comment by ravi72munde** [comment]
Answered on other repo
